services:
  - type: web
    name: ekatest
    rootDir: frontend
    plan: free
    env: static
    buildCommand: yarn build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true # optional
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
